name: bslmap
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - pip:
      - typer>=0.12
      - httpx>=0.27
      - pydantic>=2
      - pydantic-settings>=2
      - pandas>=2
      - tqdm>=4.65
      - ruff
      - black
      - mypy
      - pytest
      - pytest-cov
      - torch>=2.0.0
      - torchvision
      - torchaudio
      - transformers>=4.30.0
      - accelerate>=0.20.0
      - bitsandbytes>=0.42.0
      - sentencepiece>=0.1.99
      - protobuf>=3.20.0